# Generated by Django 2.0.4 on 2018-04-03 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180403_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Created'),
        ),
    ]
