# Generated by Django 2.0.4 on 2018-04-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creatorId',
            new_name='creator',
        ),
    ]
